// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD04wunq5WbAPofN4aVrKxl2YjhwNi4fFs',
    appId: '1:334664211266:web:42b3a7175c12ffd3c1c6db',
    messagingSenderId: '334664211266',
    projectId: 'flutterauth-3e491',
    authDomain: 'flutterauth-3e491.firebaseapp.com',
    storageBucket: 'flutterauth-3e491.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMDXKMsCoyPHv6p7LX4UL1BxY-UlM_fug',
    appId: '1:334664211266:android:3d653522fb66da31c1c6db',
    messagingSenderId: '334664211266',
    projectId: 'flutterauth-3e491',
    storageBucket: 'flutterauth-3e491.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBybCZjl2Bc0o4q8RoDOyGQQViRvM39Kq8',
    appId: '1:334664211266:ios:b5013a46cbb8cc3ac1c6db',
    messagingSenderId: '334664211266',
    projectId: 'flutterauth-3e491',
    storageBucket: 'flutterauth-3e491.firebasestorage.app',
    iosClientId: '334664211266-pdsciiuuo4gjes4c867dana5b047607u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBybCZjl2Bc0o4q8RoDOyGQQViRvM39Kq8',
    appId: '1:334664211266:ios:b5013a46cbb8cc3ac1c6db',
    messagingSenderId: '334664211266',
    projectId: 'flutterauth-3e491',
    storageBucket: 'flutterauth-3e491.firebasestorage.app',
    iosClientId: '334664211266-pdsciiuuo4gjes4c867dana5b047607u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD04wunq5WbAPofN4aVrKxl2YjhwNi4fFs',
    appId: '1:334664211266:web:89d0cc3e8000417dc1c6db',
    messagingSenderId: '334664211266',
    projectId: 'flutterauth-3e491',
    authDomain: 'flutterauth-3e491.firebaseapp.com',
    storageBucket: 'flutterauth-3e491.firebasestorage.app',
  );
}